"""
Document ingestion pipeline tests.

All PDFs used here are the SYNTHETIC TEST FIXTURES generated by
tests/fixtures/generate_test_pdfs.py — never real BIS documents. Each
fixture's own text explicitly says "SYNTHETIC TEST DOCUMENT -- NOT AN
OFFICIAL BIS STANDARD". These tests verify pipeline mechanics (does
extraction/OCR/status-tracking work), not real BIS content accuracy.
"""

from pathlib import Path

import pytest

from app.ingestion.validation import DocumentValidationError, compute_file_hash, validate_upload
from app.services.document_service import DocumentService, DuplicateDocumentError

FIXTURES_DIR = Path(__file__).parent / "fixtures"


def _read_fixture(name: str) -> bytes:
    return (FIXTURES_DIR / name).read_bytes()


# --- Validation ---


def test_valid_pdf_passes_validation():
    content = _read_fixture("test_text.pdf")
    validate_upload(content, "application/pdf", "test_text.pdf")  # should not raise


def test_invalid_file_rejected():
    content = _read_fixture("test_invalid.txt")
    with pytest.raises(DocumentValidationError, match="valid PDF"):
        validate_upload(content, "application/pdf", "test_invalid.txt")


def test_empty_content_rejected():
    with pytest.raises(DocumentValidationError, match="empty"):
        validate_upload(b"", "application/pdf", "empty.pdf")


def test_wrong_mime_type_rejected():
    content = _read_fixture("test_text.pdf")
    with pytest.raises(DocumentValidationError, match="Unsupported file type"):
        validate_upload(content, "image/png", "test_text.pdf")


def test_oversized_file_rejected():
    fake_large_content = b"%PDF-1.4\n" + b"0" * (51 * 1024 * 1024)
    with pytest.raises(DocumentValidationError, match="exceeds"):
        validate_upload(fake_large_content, "application/pdf", "big.pdf")


# --- End-to-end pipeline (service layer, isolated DB + storage) ---


def test_text_pdf_end_to_end(db_session, isolated_storage):
    service = DocumentService(db_session)
    content = _read_fixture("test_text.pdf")
    document = service.register_upload(content, "test_text.pdf", "application/pdf", source_type="test")
    assert document.status == "uploaded"

    result = service.process_document(document.id, content)
    assert result.status == "completed"
    assert result.page_count == 1
    assert result.extracted_standard_number == "IS 99999"

    pages = service.get_pages(document.id)
    assert len(pages) == 1
    assert pages[0].extraction_method == "native"
    assert "SYNTHETIC TEST DOCUMENT" in pages[0].text


def test_scanned_pdf_uses_ocr(db_session, isolated_storage):
    service = DocumentService(db_session)
    content = _read_fixture("test_scanned.pdf")
    document = service.register_upload(content, "test_scanned.pdf", "application/pdf", source_type="test")
    result = service.process_document(document.id, content)

    assert result.status == "completed"
    pages = service.get_pages(document.id)
    assert pages[0].extraction_method == "ocr"
    assert pages[0].ocr_confidence is not None
    assert pages[0].ocr_confidence > 0
    assert "IS 88888" in pages[0].text


def test_mixed_pdf_processes_each_page_independently(db_session, isolated_storage):
    service = DocumentService(db_session)
    content = _read_fixture("test_mixed.pdf")
    document = service.register_upload(content, "test_mixed.pdf", "application/pdf", source_type="test")
    result = service.process_document(document.id, content)

    assert result.status == "completed"
    assert result.page_count == 2
    pages = service.get_pages(document.id)
    methods = {p.page_number: p.extraction_method for p in pages}
    assert methods[1] == "native"
    assert methods[2] == "ocr"


def test_empty_page_document_completes_without_fabricated_metadata(db_session, isolated_storage):
    service = DocumentService(db_session)
    content = _read_fixture("test_empty.pdf")
    document = service.register_upload(content, "test_empty.pdf", "application/pdf", source_type="test")
    result = service.process_document(document.id, content)

    assert result.status == "completed"
    assert result.extracted_standard_number is None
    assert result.extracted_title is None
    assert result.extracted_edition is None


def test_duplicate_file_hash_rejected(db_session, isolated_storage):
    service = DocumentService(db_session)
    content = _read_fixture("test_text.pdf")
    first = service.register_upload(content, "test_text.pdf", "application/pdf", source_type="test")

    with pytest.raises(DuplicateDocumentError) as exc_info:
        service.register_upload(content, "test_text_renamed.pdf", "application/pdf", source_type="test")
    assert exc_info.value.existing_document_id == first.id


def test_feature_extraction_finds_standard_number_mentions(db_session, isolated_storage):
    service = DocumentService(db_session)
    content = _read_fixture("test_text.pdf")
    document = service.register_upload(content, "test_text.pdf", "application/pdf", source_type="test")
    service.process_document(document.id, content)

    features = service.get_features(document.id)
    standard_number_features = [f for f in features if f.feature_type == "standard_number"]
    values = {f.value for f in standard_number_features}
    # The fixture body text mentions both its own number and a reference to IS 302-1.
    assert "IS 99999" in values
    assert "IS 302-1" in values


def test_feature_extraction_finds_section_headings(db_session, isolated_storage):
    service = DocumentService(db_session)
    content = _read_fixture("test_text.pdf")
    document = service.register_upload(content, "test_text.pdf", "application/pdf", source_type="test")
    service.process_document(document.id, content)

    features = service.get_features(document.id)
    headings = [f.value for f in features if f.feature_type == "section_heading"]
    assert any("SCOPE" in h for h in headings)


def test_all_seeded_documents_are_marked_test_or_demo_never_verified(db_session, isolated_storage):
    service = DocumentService(db_session)
    content = _read_fixture("test_text.pdf")
    document = service.register_upload(content, "test_text.pdf", "application/pdf", source_type="test")
    assert document.source_type != "verified_bis"


# --- API layer ---


def test_upload_endpoint_registers_and_returns_document(client, isolated_storage):
    content = _read_fixture("test_text.pdf")
    response = client.post(
        "/api/documents/upload", files={"file": ("test_text.pdf", content, "application/pdf")}
    )
    assert response.status_code == 201
    body = response.json()
    assert body["status"] == "uploaded"
    assert body["original_filename"] == "test_text.pdf"


def test_upload_invalid_file_returns_422(client, isolated_storage):
    response = client.post(
        "/api/documents/upload", files={"file": ("bad.txt", b"not a pdf", "application/pdf")}
    )
    assert response.status_code == 422


def test_upload_duplicate_returns_409(client, isolated_storage):
    content = _read_fixture("test_text.pdf")
    first = client.post("/api/documents/upload", files={"file": ("a.pdf", content, "application/pdf")})
    assert first.status_code == 201

    second = client.post("/api/documents/upload", files={"file": ("b.pdf", content, "application/pdf")})
    assert second.status_code == 409


def test_get_document_not_found_returns_404(client, isolated_storage):
    response = client.get("/api/documents/does-not-exist")
    assert response.status_code == 404


def test_get_status_not_found_returns_404(client, isolated_storage):
    response = client.get("/api/documents/does-not-exist/status")
    assert response.status_code == 404


def test_get_pages_not_found_returns_404(client, isolated_storage):
    response = client.get("/api/documents/does-not-exist/pages")
    assert response.status_code == 404


def test_get_features_not_found_returns_404(client, isolated_storage):
    response = client.get("/api/documents/does-not-exist/features")
    assert response.status_code == 404


def test_get_status_reflects_uploaded_before_background_processing(client, isolated_storage):
    """Upload response returns immediately with status 'uploaded' — the
    pipeline runs as a background task, not inline, per Step 10."""
    content = _read_fixture("test_text.pdf")
    upload_response = client.post(
        "/api/documents/upload", files={"file": ("test_text.pdf", content, "application/pdf")}
    )
    document_id = upload_response.json()["id"]

    status_response = client.get(f"/api/documents/{document_id}/status")
    assert status_response.status_code == 200
    # Depending on TestClient's background-task timing this may already be
    # further along, but it must never claim "completed" from the upload
    # response itself (checked above) — the status endpoint independently
    # reflects genuine pipeline state either way.
    assert status_response.json()["status"] in {
        "uploaded",
        "processing",
        "text_extracted",
        "features_extracted",
        "completed",
    }
