"""
Phase 8 tests — real BIS document ingestion infrastructure additions:
publication_year extraction, table-structure preservation in PDF text
extraction, and the combined ingest+index CLI (app.ingestion.ingest_and_index).

All PDFs used here are the SYNTHETIC TEST FIXTURES generated by
tests/fixtures/generate_test_pdfs.py — never real BIS documents. No real
BIS PDF was available during this phase; see the Phase 8 handoff for the
explicit "REAL BIS VERIFICATION: NOT POSSIBLE" status. These tests verify
pipeline mechanics only.
"""

from pathlib import Path

import pytest

from app.ingestion.extraction import extract_pdf_pages
from app.ingestion.ingest_and_index import run as run_ingest_and_index
from app.ingestion.metadata_extraction import extract_metadata, extract_publication_year
from app.ocr.tesseract_provider import TesseractOCRProvider
from app.rag.index_document import index_document
from app.services.document_service import DocumentService

FIXTURES_DIR = Path(__file__).parent / "fixtures"


def _read_fixture(name: str) -> bytes:
    return (FIXTURES_DIR / name).read_bytes()


# --- Publication year extraction ---


def test_extract_publication_year_finds_plausible_bis_year():
    assert extract_publication_year("IS 66666 : 2021\nSome text") == "2021"


def test_extract_publication_year_returns_none_when_absent():
    assert extract_publication_year("IS 99999\nNo year mentioned here at all") is None


def test_extract_publication_year_ignores_implausible_numbers():
    # A clause-like 4-digit number outside the plausible BIS range (1950-2099)
    # must not be mistaken for a publication year.
    assert extract_publication_year("Clause 3456 refers to section 1000") is None


def test_extract_metadata_includes_publication_year_field():
    metadata = extract_metadata("IS 66666 : 2021\nSecond Revision")
    assert metadata.publication_year == "2021"
    assert metadata.edition == "Second Revision"


def test_table_fixture_extracts_standard_number_title_edition_and_year(db_session, isolated_storage):
    """End-to-end: a real ingestion run (not just the metadata extractor in
    isolation) correctly populates extracted_publication_year alongside the
    existing metadata fields, for a document that has both."""
    service = DocumentService(db_session)
    content = _read_fixture("test_table.pdf")
    document = service.register_upload(content, "test_table.pdf", "application/pdf", source_type="test")

    result = service.process_document(document.id, content)

    assert result.status == "completed"
    assert result.extracted_standard_number == "IS 66666"
    assert result.extracted_edition == "Second Revision"
    assert result.extracted_publication_year == "2021"


def test_document_with_no_year_leaves_field_null_not_guessed(db_session, isolated_storage):
    service = DocumentService(db_session)
    content = _read_fixture("test_text.pdf")
    document = service.register_upload(content, "test_text.pdf", "application/pdf", source_type="test")

    result = service.process_document(document.id, content)

    assert result.status == "completed"
    assert result.extracted_publication_year is None


# --- Table-structure preservation in extraction ---


def test_native_page_with_table_produces_delimited_table_block():
    content = _read_fixture("test_table.pdf")
    pages = extract_pdf_pages(content, TesseractOCRProvider())

    assert len(pages) == 1
    text = pages[0].text
    assert "[TABLE]" in text
    assert "[/TABLE]" in text
    # Cell values from the fixture's table must survive, pipe-delimited.
    assert "Size | Tolerance | Grade" in text
    assert "10mm | +/-0.5 | A" in text


def test_page_without_table_is_unaffected():
    content = _read_fixture("test_text.pdf")
    pages = extract_pdf_pages(content, TesseractOCRProvider())

    assert "[TABLE]" not in pages[0].text
    assert "1 SCOPE" in pages[0].text


def test_table_marker_does_not_break_downstream_chunking(db_session, isolated_storage):
    """The [TABLE] block is still plain text as far as chunking/embedding
    are concerned — indexing a table-bearing document must succeed and
    produce retrievable chunks like any other document."""
    service = DocumentService(db_session)
    content = _read_fixture("test_table.pdf")
    document = service.register_upload(content, "test_table.pdf", "application/pdf", source_type="test")
    result = service.process_document(document.id, content)
    assert result.status == "completed"

    from tests.test_embeddings import FakeEmbeddingProvider

    index_result = index_document(db_session, document.id, embedding_provider=FakeEmbeddingProvider())
    assert index_result.chunks_created > 0
    assert index_result.chunks_embedded == index_result.chunks_created


# --- Combined ingest+index CLI ---


def test_ingest_and_index_cli_reports_missing_file(tmp_path):
    missing_path = tmp_path / "does_not_exist.pdf"
    exit_code = run_ingest_and_index(str(missing_path))
    assert exit_code == 1


def test_ingest_and_index_cli_runs_full_pipeline_and_indexes(tmp_path, monkeypatch, isolated_storage):
    """Runs the real CLI entrypoint end-to-end against an isolated SQLite
    DB (never the developer's real bis_sahayak.db), verifying it performs
    registration + ingestion + indexing as one operation and reports
    success only once chunks are actually created and embedded."""
    import app.ingestion.ingest_and_index as cli_module
    from sqlalchemy import create_engine
    from sqlalchemy.orm import sessionmaker

    from tests.conftest import create_all_tables

    db_path = tmp_path / "cli_test.db"
    engine = create_engine(f"sqlite:///{db_path}", connect_args={"check_same_thread": False})
    create_all_tables(engine)
    TestSessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
    monkeypatch.setattr(cli_module, "SessionLocal", TestSessionLocal)

    fixture_copy = tmp_path / "test_text.pdf"
    fixture_copy.write_bytes(_read_fixture("test_text.pdf"))

    exit_code = run_ingest_and_index(str(fixture_copy))
    assert exit_code == 0

    session = TestSessionLocal()
    try:
        from app.models.document_chunk import DocumentChunk
        from app.models.standard_document import StandardDocument

        documents = session.query(StandardDocument).all()
        assert len(documents) == 1
        assert documents[0].status == "completed"

        chunks = session.query(DocumentChunk).filter_by(document_id=documents[0].id).all()
        assert len(chunks) > 0
        assert all(c.embedding_json is not None for c in chunks)
    finally:
        session.close()
    engine.dispose()


def test_ingest_and_index_cli_reports_duplicate_without_reindexing(tmp_path, monkeypatch, isolated_storage):
    import app.ingestion.ingest_and_index as cli_module
    from sqlalchemy import create_engine
    from sqlalchemy.orm import sessionmaker

    from tests.conftest import create_all_tables

    db_path = tmp_path / "cli_dup_test.db"
    engine = create_engine(f"sqlite:///{db_path}", connect_args={"check_same_thread": False})
    create_all_tables(engine)
    TestSessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
    monkeypatch.setattr(cli_module, "SessionLocal", TestSessionLocal)

    fixture_copy = tmp_path / "test_text.pdf"
    fixture_copy.write_bytes(_read_fixture("test_text.pdf"))

    first_exit_code = run_ingest_and_index(str(fixture_copy))
    assert first_exit_code == 0

    second_exit_code = run_ingest_and_index(str(fixture_copy))
    assert second_exit_code == 1  # reported as already-ingested, not silently duplicated

    session = TestSessionLocal()
    try:
        from app.models.standard_document import StandardDocument

        documents = session.query(StandardDocument).all()
        assert len(documents) == 1  # no duplicate row created
    finally:
        session.close()
    engine.dispose()


def test_ingest_and_index_cli_reports_pipeline_failure_without_indexing(tmp_path, monkeypatch, isolated_storage):
    """A corrupt/invalid PDF must fail at the ingestion stage and never
    reach indexing — the CLI must report which stage failed."""
    import app.ingestion.ingest_and_index as cli_module
    from sqlalchemy import create_engine
    from sqlalchemy.orm import sessionmaker

    from tests.conftest import create_all_tables

    db_path = tmp_path / "cli_fail_test.db"
    engine = create_engine(f"sqlite:///{db_path}", connect_args={"check_same_thread": False})
    create_all_tables(engine)
    TestSessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
    monkeypatch.setattr(cli_module, "SessionLocal", TestSessionLocal)

    # A validation failure (invalid file) is caught before any document is
    # even registered — a distinct, earlier failure point than a pipeline
    # failure, and it must also report cleanly rather than crashing.
    invalid_copy = tmp_path / "test_invalid.txt"
    invalid_copy.write_bytes(_read_fixture("test_invalid.txt"))
    # validate_upload rejects based on mime_type/header; the CLI always
    # passes mime_type="application/pdf", so this exercises the missing
    # %PDF- header check specifically.
    exit_code = run_ingest_and_index(str(invalid_copy))
    assert exit_code == 1

    session = TestSessionLocal()
    try:
        from app.models.standard_document import StandardDocument

        assert session.query(StandardDocument).count() == 0
    finally:
        session.close()
    engine.dispose()
