"""
Phase 9 tests — document-management API (list, delete, reindex) and the
auto-indexing wired into the upload background task.

All PDFs used here are the SYNTHETIC TEST FIXTURES generated by
tests/fixtures/generate_test_pdfs.py — never real BIS documents. No real
BIS PDF was available during this phase.
"""

from pathlib import Path

from app.rag.index_document import IndexingError
from app.services.document_service import DocumentService, DuplicateDocumentError

FIXTURES_DIR = Path(__file__).parent / "fixtures"


def _read_fixture(name: str) -> bytes:
    return (FIXTURES_DIR / name).read_bytes()


# --- Auto-indexing wired into upload/process ---


def test_process_document_auto_indexes_after_pipeline_completes(db_session, isolated_storage):
    service = DocumentService(db_session)
    content = _read_fixture("test_text.pdf")
    document = service.register_upload(content, "test_text.pdf", "application/pdf", source_type="test")

    result = service.process_document(document.id, content)

    assert result.status == "completed"
    assert result.chunk_count > 0
    assert result.display_status == "INDEXED"


def test_upload_endpoint_document_becomes_indexed_and_retrievable(client, isolated_storage):
    content = _read_fixture("test_text.pdf")
    upload_response = client.post("/api/documents/upload", files={"file": ("test_text.pdf", content, "application/pdf")})
    document_id = upload_response.json()["id"]

    get_response = client.get(f"/api/documents/{document_id}")
    body = get_response.json()
    assert body["display_status"] == "INDEXED"
    assert body["chunk_count"] > 0

    retrieve_response = client.post("/api/rag/retrieve", json={"query": "synthetic document scope", "top_k": 4})
    assert retrieve_response.status_code == 200
    assert len(retrieve_response.json()["results"]) > 0


def test_empty_page_document_completes_but_is_not_indexed(db_session, isolated_storage):
    """A document with zero extractable text produces zero chunks — it must
    honestly report PROCESSING (never fabricate INDEXED), matching the
    existing 'do not silently ingest a document with no usable text'
    principle from validation, extended to the display status."""
    service = DocumentService(db_session)
    content = _read_fixture("test_empty.pdf")
    document = service.register_upload(content, "test_empty.pdf", "application/pdf", source_type="test")

    result = service.process_document(document.id, content)

    assert result.status == "completed"
    assert result.chunk_count == 0
    assert result.display_status == "PROCESSING"


def test_failed_pipeline_reports_failed_display_status(db_session, isolated_storage):
    from app.ocr.provider import OCRProvider

    class AlwaysFailingOCR(OCRProvider):
        def extract_text(self, image):
            raise RuntimeError("OCR provider unavailable")

    service = DocumentService(db_session, ocr_provider=AlwaysFailingOCR())
    content = _read_fixture("test_scanned.pdf")
    document = service.register_upload(content, "test_scanned.pdf", "application/pdf", source_type="test")

    result = service.process_document(document.id, content)

    assert result.status == "failed"
    assert result.display_status == "FAILED"
    assert result.chunk_count == 0


# --- Document listing ---


def test_list_documents_returns_all_documents(db_session, isolated_storage):
    service = DocumentService(db_session)
    content_a = _read_fixture("test_text.pdf")
    content_b = _read_fixture("test_table.pdf")
    service.register_upload(content_a, "a.pdf", "application/pdf", source_type="test")
    service.register_upload(content_b, "b.pdf", "application/pdf", source_type="test")

    documents = service.list_documents()

    assert len(documents) == 2
    filenames = {d.original_filename for d in documents}
    assert filenames == {"a.pdf", "b.pdf"}


def test_list_documents_endpoint_returns_expected_fields(client, isolated_storage):
    content = _read_fixture("test_table.pdf")
    upload_response = client.post("/api/documents/upload", files={"file": ("test_table.pdf", content, "application/pdf")})
    document_id = upload_response.json()["id"]

    list_response = client.get("/api/documents")
    assert list_response.status_code == 200
    documents = list_response.json()
    assert len(documents) == 1
    doc = documents[0]

    assert doc["id"] == document_id
    assert doc["original_filename"] == "test_table.pdf"
    assert "standard_id" in doc
    assert "chunk_count" in doc
    assert "display_status" in doc
    assert "extracted_publication_year" in doc
    assert "file_hash" in doc
    # Filesystem paths must never be exposed to the frontend.
    assert "storage_path" not in doc


def test_list_documents_empty_when_none_uploaded(client, isolated_storage):
    response = client.get("/api/documents")
    assert response.status_code == 200
    assert response.json() == []


# --- Delete ---


def test_delete_document_removes_row_and_cascades_chunks(db_session, isolated_storage):
    service = DocumentService(db_session)
    content = _read_fixture("test_text.pdf")
    document = service.register_upload(content, "test_text.pdf", "application/pdf", source_type="test")
    service.process_document(document.id, content)
    assert service.get_document(document.id) is not None

    deleted = service.delete_document(document.id)

    assert deleted is True
    assert service.get_document(document.id) is None

    from app.models.document_chunk import DocumentChunk

    remaining_chunks = db_session.query(DocumentChunk).filter_by(document_id=document.id).count()
    assert remaining_chunks == 0


def test_delete_document_removes_stored_file(db_session, isolated_storage):
    service = DocumentService(db_session)
    content = _read_fixture("test_text.pdf")
    document_response = service.register_upload(content, "test_text.pdf", "application/pdf", source_type="test")

    from app.repositories.document_repository import DocumentRepository

    stored_document = DocumentRepository(db_session).get_by_id(document_response.id)
    storage_path = Path(stored_document.storage_path)
    assert storage_path.exists()

    service.delete_document(document_response.id)

    assert not storage_path.exists()


def test_delete_nonexistent_document_returns_false(db_session, isolated_storage):
    service = DocumentService(db_session)
    assert service.delete_document("does-not-exist") is False


def test_delete_document_endpoint_returns_204_then_404_on_second_delete(client, isolated_storage):
    content = _read_fixture("test_text.pdf")
    upload_response = client.post("/api/documents/upload", files={"file": ("test_text.pdf", content, "application/pdf")})
    document_id = upload_response.json()["id"]

    first_delete = client.delete(f"/api/documents/{document_id}")
    assert first_delete.status_code == 204

    second_delete = client.delete(f"/api/documents/{document_id}")
    assert second_delete.status_code == 404

    get_response = client.get(f"/api/documents/{document_id}")
    assert get_response.status_code == 404


def test_deleting_a_document_does_not_affect_other_documents(client, isolated_storage):
    content_a = _read_fixture("test_text.pdf")
    content_b = _read_fixture("test_table.pdf")
    doc_a = client.post("/api/documents/upload", files={"file": ("a.pdf", content_a, "application/pdf")}).json()
    doc_b = client.post("/api/documents/upload", files={"file": ("b.pdf", content_b, "application/pdf")}).json()

    client.delete(f"/api/documents/{doc_a['id']}")

    assert client.get(f"/api/documents/{doc_a['id']}").status_code == 404
    assert client.get(f"/api/documents/{doc_b['id']}").status_code == 200


# --- Reindex ---


def test_reindex_document_recreates_chunks(db_session, isolated_storage):
    service = DocumentService(db_session)
    content = _read_fixture("test_text.pdf")
    document = service.register_upload(content, "test_text.pdf", "application/pdf", source_type="test")
    first_result = service.process_document(document.id, content)
    assert first_result.chunk_count > 0

    reindexed = service.reindex_document(document.id)

    assert reindexed.chunk_count == first_result.chunk_count
    assert reindexed.display_status == "INDEXED"


def test_reindex_uncompleted_document_raises(db_session, isolated_storage):
    service = DocumentService(db_session)
    content = _read_fixture("test_text.pdf")
    document = service.register_upload(content, "test_text.pdf", "application/pdf", source_type="test")
    # Deliberately not calling process_document — status stays "uploaded".

    try:
        service.reindex_document(document.id)
        assert False, "expected IndexingError"
    except IndexingError:
        pass


def test_reindex_nonexistent_document_returns_none(db_session, isolated_storage):
    service = DocumentService(db_session)
    assert service.reindex_document("does-not-exist") is None


def test_reindex_endpoint_returns_404_for_nonexistent_document(client, isolated_storage):
    reindex_response = client.post("/api/documents/does-not-exist/reindex")
    assert reindex_response.status_code == 404


def test_reindex_endpoint_success(client, isolated_storage):
    content = _read_fixture("test_text.pdf")
    upload_response = client.post("/api/documents/upload", files={"file": ("test_text.pdf", content, "application/pdf")})
    document_id = upload_response.json()["id"]

    reindex_response = client.post(f"/api/documents/{document_id}/reindex")
    assert reindex_response.status_code == 200
    assert reindex_response.json()["display_status"] == "INDEXED"


# --- source_type governance ---


def test_uploaded_document_never_becomes_verified_bis(client, isolated_storage):
    content = _read_fixture("test_text.pdf")
    upload_response = client.post("/api/documents/upload", files={"file": ("test_text.pdf", content, "application/pdf")})
    body = upload_response.json()

    assert body["source_type"] != "verified_bis"
    assert body["source_type"] == "unverified"  # the API's default, never inferred as verified

    document_id = body["id"]
    get_response = client.get(f"/api/documents/{document_id}")
    assert get_response.json()["source_type"] != "verified_bis"


def test_reindexing_does_not_change_source_type(db_session, isolated_storage):
    service = DocumentService(db_session)
    content = _read_fixture("test_text.pdf")
    document = service.register_upload(content, "test_text.pdf", "application/pdf", source_type="test")
    service.process_document(document.id, content)

    reindexed = service.reindex_document(document.id)

    assert reindexed.source_type == "test"
    assert reindexed.source_type != "verified_bis"


# --- Duplicate detection surfaced through document management ---


def test_duplicate_upload_reports_existing_document_id(db_session, isolated_storage):
    service = DocumentService(db_session)
    content = _read_fixture("test_text.pdf")
    first = service.register_upload(content, "a.pdf", "application/pdf", source_type="test")

    try:
        service.register_upload(content, "b.pdf", "application/pdf", source_type="test")
        assert False, "expected DuplicateDocumentError"
    except DuplicateDocumentError as exc:
        assert exc.existing_document_id == first.id

    # Duplicate must not create a second document row.
    assert len(service.list_documents()) == 1


# --- Path traversal / unsafe filename handling ---


def test_unsafe_filename_does_not_escape_storage_directory(db_session, isolated_storage):
    """original_filename is stored purely as display metadata — the actual
    file is always written under {storage}/processed/{uuid}.pdf, never
    derived from the (attacker-controlled) uploaded filename. This locks in
    that guarantee rather than merely asserting the upload didn't crash."""
    service = DocumentService(db_session)
    content = _read_fixture("test_text.pdf")
    malicious_filename = "../../../../etc/passwd.pdf"

    document = service.register_upload(content, malicious_filename, "application/pdf", source_type="test")

    from app.repositories.document_repository import DocumentRepository

    stored = DocumentRepository(db_session).get_by_id(document.id)
    storage_root = isolated_storage.resolve()
    actual_path = Path(stored.storage_path).resolve()

    assert actual_path.is_relative_to(storage_root)
    assert document.original_filename == malicious_filename  # preserved for display only, never used as a path


def test_unsafe_filename_via_upload_endpoint_stays_contained(client, isolated_storage):
    content = _read_fixture("test_text.pdf")
    response = client.post(
        "/api/documents/upload",
        files={"file": ("../../../../etc/passwd.pdf", content, "application/pdf")},
    )
    assert response.status_code == 201

    storage_root = (isolated_storage / "processed").resolve()
    assert storage_root.exists()
    files_in_storage = list(storage_root.glob("*.pdf"))
    assert len(files_in_storage) == 1
    assert files_in_storage[0].resolve().is_relative_to(isolated_storage.resolve())
