"""initial schema

Revision ID: 1770f4814979
Revises: 
Create Date: 2026-09-17 14:17:16.130517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1770f4814979'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certification_schemes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('average_duration_days', sa.Integer(), nullable=False),
    sa.Column('fees', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_certification_schemes_name')
    )
    op.create_index(op.f('ix_certification_schemes_name'), 'certification_schemes', ['name'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_updated_at'), 'conversations', ['updated_at'], unique=False)
    op.create_table('labs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=False),
    sa.Column('contact', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_labs_city'), 'labs', ['city'], unique=False)
    op.create_index(op.f('ix_labs_name'), 'labs', ['name'], unique=False)
    op.create_table('standards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_amended', sa.Date(), nullable=False),
    sa.Column('sector', sa.String(length=120), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_standards_code')
    )
    op.create_index(op.f('ix_standards_category'), 'standards', ['category'], unique=False)
    op.create_index(op.f('ix_standards_code'), 'standards', ['code'], unique=False)
    op.create_index(op.f('ix_standards_title'), 'standards', ['title'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_key', sa.String(length=64), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_key', name='uq_user_preferences_user_key')
    )
    op.create_index(op.f('ix_user_preferences_user_key'), 'user_preferences', ['user_key'], unique=False)
    op.create_table('certification_steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scheme_id', sa.String(length=36), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['scheme_id'], ['certification_schemes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certification_steps_scheme_id'), 'certification_steps', ['scheme_id'], unique=False)
    op.create_table('lab_accreditations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lab_id', sa.String(length=36), nullable=False),
    sa.Column('accreditation', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_accreditations_lab_id'), 'lab_accreditations', ['lab_id'], unique=False)
    op.create_table('lab_test_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lab_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_test_categories_category'), 'lab_test_categories', ['category'], unique=False)
    op.create_index(op.f('ix_lab_test_categories_lab_id'), 'lab_test_categories', ['lab_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_table('scheme_eligibility_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scheme_id', sa.String(length=36), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('requirement', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['scheme_id'], ['certification_schemes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheme_eligibility_items_scheme_id'), 'scheme_eligibility_items', ['scheme_id'], unique=False)
    op.create_table('standard_related_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('standard_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['standard_id'], ['standards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_standard_related_codes_standard_id'), 'standard_related_codes', ['standard_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_standard_related_codes_standard_id'), table_name='standard_related_codes')
    op.drop_table('standard_related_codes')
    op.drop_index(op.f('ix_scheme_eligibility_items_scheme_id'), table_name='scheme_eligibility_items')
    op.drop_table('scheme_eligibility_items')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_lab_test_categories_lab_id'), table_name='lab_test_categories')
    op.drop_index(op.f('ix_lab_test_categories_category'), table_name='lab_test_categories')
    op.drop_table('lab_test_categories')
    op.drop_index(op.f('ix_lab_accreditations_lab_id'), table_name='lab_accreditations')
    op.drop_table('lab_accreditations')
    op.drop_index(op.f('ix_certification_steps_scheme_id'), table_name='certification_steps')
    op.drop_table('certification_steps')
    op.drop_index(op.f('ix_user_preferences_user_key'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_standards_title'), table_name='standards')
    op.drop_index(op.f('ix_standards_code'), table_name='standards')
    op.drop_index(op.f('ix_standards_category'), table_name='standards')
    op.drop_table('standards')
    op.drop_index(op.f('ix_labs_name'), table_name='labs')
    op.drop_index(op.f('ix_labs_city'), table_name='labs')
    op.drop_table('labs')
    op.drop_index(op.f('ix_conversations_updated_at'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_certification_schemes_name'), table_name='certification_schemes')
    op.drop_table('certification_schemes')
    # ### end Alembic commands ###
