"""phase 3 document ingestion tables

Revision ID: 440d97c5a48f
Revises: 1770f4814979
Create Date: 2026-09-17 18:29:12.265301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '440d97c5a48f'
down_revision: Union[str, None] = '1770f4814979'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('standard_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('standard_id', sa.String(length=36), nullable=True),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('extracted_standard_number', sa.String(length=50), nullable=True),
    sa.Column('extracted_title', sa.String(length=500), nullable=True),
    sa.Column('extracted_edition', sa.String(length=100), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['standard_id'], ['standards.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash', name='uq_standard_documents_file_hash')
    )
    op.create_index(op.f('ix_standard_documents_file_hash'), 'standard_documents', ['file_hash'], unique=False)
    op.create_index(op.f('ix_standard_documents_standard_id'), 'standard_documents', ['standard_id'], unique=False)
    op.create_index(op.f('ix_standard_documents_status'), 'standard_documents', ['status'], unique=False)
    op.create_table('document_features',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('feature_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['standard_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_features_document_id'), 'document_features', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_features_feature_type'), 'document_features', ['feature_type'], unique=False)
    op.create_table('document_pages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('extraction_method', sa.String(length=10), nullable=False),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['standard_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'page_number', name='uq_document_pages_document_page')
    )
    op.create_index(op.f('ix_document_pages_document_id'), 'document_pages', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_pages_document_id'), table_name='document_pages')
    op.drop_table('document_pages')
    op.drop_index(op.f('ix_document_features_feature_type'), table_name='document_features')
    op.drop_index(op.f('ix_document_features_document_id'), table_name='document_features')
    op.drop_table('document_features')
    op.drop_index(op.f('ix_standard_documents_status'), table_name='standard_documents')
    op.drop_index(op.f('ix_standard_documents_standard_id'), table_name='standard_documents')
    op.drop_index(op.f('ix_standard_documents_file_hash'), table_name='standard_documents')
    op.drop_table('standard_documents')
    # ### end Alembic commands ###
