"""phase_12_document_taxonomy_provenance_regulatory_evidence

Revision ID: 4e502eccb1e7
Revises: c767a562bd5d
Create Date: 2026-09-17 23:02:07.057803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e502eccb1e7'
down_revision: Union[str, None] = 'c767a562bd5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # NOTE: the autogenerated diff also proposed dropping
    # document_chunks_fts and its internal shadow tables
    # (document_chunks_fts_data/_idx/_config/_content/_docsize). That is a
    # false positive: those tables are FTS5's own internal storage for the
    # hand-written virtual table created in
    # c767a562bd5d_phase_10_product_profile.py — SQLAlchemy has no ORM
    # model for a virtual table, so autogenerate always sees it as
    # "unknown, therefore removed." Those drop/recreate statements have
    # been removed from this migration; the FTS5 table is untouched by
    # Phase 12.
    op.create_table('regulatory_evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('regulatory_reference', sa.String(length=500), nullable=True),
    sa.Column('product_scope', sa.Text(), nullable=True),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mandatory_status', sa.String(length=20), nullable=False),
    sa.Column('scheme', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['standard_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regulatory_evidence_document_id'), 'regulatory_evidence', ['document_id'], unique=True)
    op.create_table('regulatory_evidence_related_standards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('regulatory_evidence_id', sa.String(length=36), nullable=False),
    sa.Column('standard_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['regulatory_evidence_id'], ['regulatory_evidence.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['standard_id'], ['standards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regulatory_evidence_related_standards_regulatory_evidence_id'), 'regulatory_evidence_related_standards', ['regulatory_evidence_id'], unique=False)
    op.create_index(op.f('ix_regulatory_evidence_related_standards_standard_id'), 'regulatory_evidence_related_standards', ['standard_id'], unique=False)
    # server_default ensures existing rows backfill to 'OTHER' rather than
    # violating the NOT NULL constraint (see DEFAULT_DOCUMENT_TYPE in
    # app/product/document_type.py).
    op.add_column(
        'standard_documents',
        sa.Column('document_type', sa.String(length=30), nullable=False, server_default='OTHER'),
    )
    op.add_column('standard_documents', sa.Column('source', sa.String(length=255), nullable=True))
    op.add_column('standard_documents', sa.Column('source_url', sa.Text(), nullable=True))
    op.add_column('standard_documents', sa.Column('acquisition_date', sa.DateTime(timezone=True), nullable=True))


def downgrade() -> None:
    op.drop_column('standard_documents', 'acquisition_date')
    op.drop_column('standard_documents', 'source_url')
    op.drop_column('standard_documents', 'source')
    op.drop_column('standard_documents', 'document_type')
    op.drop_index(op.f('ix_regulatory_evidence_related_standards_standard_id'), table_name='regulatory_evidence_related_standards')
    op.drop_index(op.f('ix_regulatory_evidence_related_standards_regulatory_evidence_id'), table_name='regulatory_evidence_related_standards')
    op.drop_table('regulatory_evidence_related_standards')
    op.drop_index(op.f('ix_regulatory_evidence_document_id'), table_name='regulatory_evidence')
    op.drop_table('regulatory_evidence')
