"""scope conversations to users

Revision ID: 7b1a21f93df3
Revises: ee6f2295b254
Create Date: 2026-09-18 02:49:12.361125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b1a21f93df3'
down_revision: Union[str, None] = 'ee6f2295b254'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # NOTE: the autogenerated diff also proposed dropping
    # document_chunks_fts and its internal shadow tables — the same known
    # false positive documented in earlier migrations (SQLAlchemy has no
    # ORM model for that hand-written FTS5 virtual table). Those
    # drop/recreate statements have been removed from this migration.
    #
    # NOTE 2: adding a column with a foreign key constraint requires
    # SQLite's "batch mode" (copy-and-move) — plain op.add_column() +
    # op.create_foreign_key() raises NotImplementedError on this dialect
    # ("No support for ALTER of constraints in SQLite dialect"), confirmed
    # by actually running this migration. batch_alter_table handles this
    # by rebuilding the table under the hood.
    with op.batch_alter_table("conversations") as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.String(length=36), nullable=True))
        batch_op.create_index(op.f("ix_conversations_user_id"), ["user_id"], unique=False)
        batch_op.create_foreign_key(
            "fk_conversations_user_id_users", "users", ["user_id"], ["id"], ondelete="CASCADE"
        )


def downgrade() -> None:
    with op.batch_alter_table("conversations") as batch_op:
        batch_op.drop_constraint("fk_conversations_user_id_users", type_="foreignkey")
        batch_op.drop_index(op.f("ix_conversations_user_id"))
        batch_op.drop_column("user_id")
