"""phase_10_product_profile

Revision ID: c767a562bd5d
Revises: f85f6fc9457a
Create Date: 2026-09-17 22:06:37.374566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c767a562bd5d'
down_revision: Union[str, None] = 'f85f6fc9457a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('product_category', sa.String(length=100), nullable=True),
    sa.Column('product_type', sa.String(length=255), nullable=True),
    sa.Column('intended_use', sa.String(length=100), nullable=True),
    sa.Column('target_market', sa.String(length=100), nullable=True),
    sa.Column('manufacturing_location', sa.String(length=255), nullable=True),
    sa.Column('electrical_characteristics', sa.String(length=255), nullable=True),
    sa.Column('capacity', sa.String(length=255), nullable=True),
    sa.Column('materials', sa.String(length=500), nullable=True),
    sa.Column('technology', sa.String(length=255), nullable=True),
    sa.Column('application', sa.String(length=255), nullable=True),
    sa.Column('other_attributes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_profiles_conversation_id'), 'product_profiles', ['conversation_id'], unique=True)
    # ### end Alembic commands ###

    # Phase 10 — hand-written (not autogenerated: Alembic/SQLAlchemy have no
    # native representation of an FTS5 virtual table). Standalone table
    # (not "external content" mode) because DocumentChunk.id is a UUID
    # string, not an INTEGER PRIMARY KEY rowid — see
    # app/rag/keyword_search.py's module docstring for the full rationale.
    # Kept in sync with DocumentChunk explicitly by app/rag/index_document.py
    # (on index/reindex) and app/services/document_service.py (on delete),
    # not by any DB-level trigger.
    op.execute(
        "CREATE VIRTUAL TABLE document_chunks_fts USING fts5("
        "chunk_id UNINDEXED, document_id UNINDEXED, text"
        ")"
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS document_chunks_fts")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_profiles_conversation_id'), table_name='product_profiles')
    op.drop_table('product_profiles')
    # ### end Alembic commands ###
