"""standard scope and requirements feature tables

Revision ID: f2657c79dd6f
Revises: 4e502eccb1e7
Create Date: 2026-09-18 02:04:19.673810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2657c79dd6f'
down_revision: Union[str, None] = '4e502eccb1e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # NOTE: the autogenerated diff also proposed dropping
    # document_chunks_fts and its internal shadow tables — the same
    # false positive documented in
    # 4e502eccb1e7_phase_12_document_taxonomy_provenance_.py (SQLAlchemy
    # has no ORM model for that hand-written FTS5 virtual table, so
    # autogenerate always sees it as "unknown, therefore removed"). Those
    # drop/recreate statements have been removed from this migration.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('standard_requirements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('clause_number', sa.String(length=50), nullable=True),
    sa.Column('requirement_text', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('referenced_standards', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['standard_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_standard_requirements_category'), 'standard_requirements', ['category'], unique=False)
    op.create_index(op.f('ix_standard_requirements_document_id'), 'standard_requirements', ['document_id'], unique=False)
    op.create_table('standard_scopes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('scope_text', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['standard_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', name='uq_standard_scopes_document_id')
    )
    op.create_index(op.f('ix_standard_scopes_document_id'), 'standard_scopes', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_standard_scopes_document_id'), table_name='standard_scopes')
    op.drop_table('standard_scopes')
    op.drop_index(op.f('ix_standard_requirements_document_id'), table_name='standard_requirements')
    op.drop_index(op.f('ix_standard_requirements_category'), table_name='standard_requirements')
    op.drop_table('standard_requirements')
    # ### end Alembic commands ###
