"""phase_8_publication_year

Revision ID: f85f6fc9457a
Revises: 0b55be269283
Create Date: 2026-09-17 21:40:54.838959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f85f6fc9457a'
down_revision: Union[str, None] = '0b55be269283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('standard_documents', sa.Column('extracted_publication_year', sa.String(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('standard_documents', 'extracted_publication_year')
    # ### end Alembic commands ###
